### ISSUE TITLE
Can you please add an example how to package a library?

### ISSUE THREAD

**Issue by charbull** [kaspersorensen/dotnet-maven-plugin#17]
Hello, 
I like this plugin ! :+1: 
can you please provide an example to package a library ?

Thank you!

**Comment by kaspersorensen** [comment]
Hi there @charbull,

Did you take a look at the example projects (https://github.com/kaspersorensen/dotnet-maven-plugin/tree/master/example-projects)?

**Comment by charbull** [comment]
Hi @kaspersorensen thank you for your reply,
I am trying to do the following, I have some cs classes generated automatically from Java.
And I am trying to package those files in a library.
This means I have to generate a [project.json](https://docs.microsoft.com/en-us/dotnet/core/tools/project-json-to-csproj) and pass it to the maven plugin?

**Comment by kaspersorensen** [comment]
yes, either project.json or a .csproj file.

**Comment by charbull** [comment]
Hey @kaspersorensen , a quick question:
Say that my cs code depends on nuget A, B, and C.
What is the best way to proceed ?

1. Should I download the dependencies A, B, and C and add them?
2. can the plugin download these dependencies?
3. I should not add these dependencies to the generated nuget?

thank you

**Comment by kaspersorensen** [comment]
Add them to the project.json or .csproj file to have it resolve those dependencies. But again, that has nothing to do with this plugin, just the ´dotnet´ build command that it fires.
