### ISSUE TITLE
[Question/Issue?] The target "pack" does not exist in the project

### ISSUE THREAD

**Issue by charbull** [kaspersorensen/dotnet-maven-plugin#18]
Hello,

I made some progress, I am able to generate the dll file
However, I am getting "The target "pack" does not exist in the project."

I am not familiar with the .net environment, I looked online:
one of the solutions suggests adding the import project and creating a .sln file as well [here](https://stackoverflow.com/questions/12036112/msbuild-project-specific-targets-for-solution-does-not-work).
I tried it as well but didn't work.

I attached my [saref.csproj](https://github.com/kaspersorensen/dotnet-maven-plugin/files/1108550/saref.csproj.txt)

any ideas?
Thank you for your help,

**Comment by kaspersorensen** [comment]
If ´dotnet pack´ is not usable for whatever reason on your project, you can turn it off in the plugins configuration:
´´´
<packEnabled>false</packEnabled>
´´´
